package com.gvw.gvwbackend.exception.handler;

import com.gvw.gvwbackend.dto.response.ErrorResponseDTO;
import com.gvw.gvwbackend.exception.*;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.client.HttpStatusCodeException;

/**
 * Global exception handler responsible for converting backend exceptions into standardized API
 * error responses.
 *
 * <p>This handler catches exceptions thrown throughout the application and maps them to:
 *
 * <ul>
 *   <li>HTTP status codes
 *   <li>GVW-specific error codes
 *   <li>Optional additional response details
 * </ul>
 *
 * <p>All responses generated by this handler include the {@code X-GVW-Error-Code} header so clients
 * can access the error code independently from the response body.
 */
@RestControllerAdvice
public class GlobalExceptionHandler {
  private static final Logger log = LoggerFactory.getLogger(GlobalExceptionHandler.class);

  @ExceptionHandler(DatabaseConnectionException.class)
  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
  public ResponseEntity<ErrorResponseDTO> handleDatabaseConnection(DatabaseConnectionException ex) {
    return generateResponse("0000500", null, HttpStatus.INTERNAL_SERVER_ERROR);
  }

  @ExceptionHandler(DatabaseMappingException.class)
  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
  public ResponseEntity<ErrorResponseDTO> handleDatabaseMapping(DatabaseMappingException ex) {
    return generateResponse("0000500", null, HttpStatus.INTERNAL_SERVER_ERROR);
  }

  @ExceptionHandler(BadRequestException.class)
  @ResponseStatus(HttpStatus.BAD_REQUEST)
  public ResponseEntity<ErrorResponseDTO> handleBadRequest(BadRequestException ex) {
    return generateResponse(ex.getMessage(), null, HttpStatus.BAD_REQUEST);
  }

  /**
   * Handles validation failures caused by {@code @Valid} request validation.
   *
   * <p>Unlike manually thrown {@link BadRequestException}s, validation failures do not contain a
   * predefined GVW error code. The error context is therefore resolved from the {@link
   * ErrorContext} annotation placed on the controller method or class.
   *
   * <p>If no error context is available, a generic validation error code is returned.
   */
  @ExceptionHandler(MethodArgumentNotValidException.class)
  @ResponseStatus(HttpStatus.BAD_REQUEST)
  public ResponseEntity<ErrorResponseDTO> handleBadRequestFromValidation(
      MethodArgumentNotValidException ex) {
    ErrorDomain domain;
    ErrorAction action;
    ErrorResource resource;

    java.lang.reflect.Method executable =
        (java.lang.reflect.Method) ex.getParameter().getExecutable();

    ErrorContext context = executable.getAnnotation(ErrorContext.class);

    if (context == null) {
      context = executable.getDeclaringClass().getAnnotation(ErrorContext.class);
    }

    if (context != null) {
      domain = context.domain();
      action = context.action();
      resource = context.resource();

      long code = domain.createCode(action, 400, resource);
      return generateResponse(String.valueOf(code), null, HttpStatus.BAD_REQUEST);
    } else {
      log.warn("Missing @ErrorContext annotation");
      ;
      return generateResponse("0000400", null, HttpStatus.BAD_REQUEST);
    }
  }

  @ExceptionHandler(InvalidCredentialsException.class)
  @ResponseStatus(HttpStatus.UNAUTHORIZED)
  public ResponseEntity<ErrorResponseDTO> handleInvalidCredentials(InvalidCredentialsException ex) {
    return generateResponse(ex.getMessage(), null, HttpStatus.UNAUTHORIZED);
  }

  @ExceptionHandler(NotFoundException.class)
  @ResponseStatus(HttpStatus.NOT_FOUND)
  public ResponseEntity<ErrorResponseDTO> handleNotFound(NotFoundException ex) {
    return generateResponse(ex.getMessage(), null, HttpStatus.NOT_FOUND);
  }

  @ExceptionHandler(HttpStatusCodeException.class)
  public ResponseEntity<ErrorResponseDTO> handleNotFoundFromDB(HttpStatusCodeException ex) {
    // This should be handled as a generic 500 error by the frontend!
    return generateResponse("0000500", null, HttpStatus.INTERNAL_SERVER_ERROR);
  }

  @ExceptionHandler(ConflictException.class)
  @ResponseStatus(HttpStatus.CONFLICT)
  public ResponseEntity<ErrorResponseDTO> handleConflict(ConflictException ex) {
    return generateResponse(ex.getMessage(), null, HttpStatus.CONFLICT);
  }

  @ExceptionHandler(TooManyRequestsException.class)
  @ResponseStatus(HttpStatus.TOO_MANY_REQUESTS)
  public ResponseEntity<ErrorResponseDTO> handleTooManyRequests(TooManyRequestsException ex) {
    return generateResponse(
        ex.getMessage(),
        Map.of("retryAfter", ex.getRetryAfterSeconds()),
        HttpStatus.TOO_MANY_REQUESTS);
  }

  /**
   * Handles unexpected exceptions that are not explicitly mapped.
   *
   * <p>Internal exception details are intentionally not exposed to clients. The frontend receives
   * only a generic internal server error code.
   */
  @ExceptionHandler(Exception.class)
  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
  public ResponseEntity<ErrorResponseDTO> handleGeneric(Exception ex) {
    return generateResponse("0000500", null, HttpStatus.INTERNAL_SERVER_ERROR);
  }

  /**
   * Creates a standardized error response used by the frontend.
   *
   * <p>The generated response contains:
   *
   * <ul>
   *   <li>The GVW error code in the response body
   *   <li>Optional additional error details
   *   <li>The GVW error code as an HTTP header
   * </ul>
   *
   * <p>The {@code X-GVW-Error-Code} header is exposed through CORS so browser clients can access it
   * from JavaScript.
   *
   * @param code GVW error code identifying the failure
   * @param details optional additional information about the error
   * @param status HTTP status returned to the client
   * @return standardized error response entity
   */
  private ResponseEntity<ErrorResponseDTO> generateResponse(
      String code, Map<String, Object> details, HttpStatus status) {
    ErrorResponseDTO dto = new ErrorResponseDTO(code, details);

    HttpHeaders headers = new HttpHeaders();
    headers.add("X-GVW-Error-Code", code);

    headers.add(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, "X-GVW-Error-Code");

    return new ResponseEntity<>(dto, headers, status);
  }
}
