package com.gvw.gvwbackend.service;

import java.security.SecureRandom;
import java.util.Base64;

/**
 * Utility class for generating cryptographically secure random tokens.
 *
 * <p>Uses {@link SecureRandom} to generate random byte sequences and encodes them using Base64
 * without padding characters.
 */
public class TokenUtils {
  private static final SecureRandom secureRandom = new SecureRandom();

  /**
   * Generates a random token with the specified byte length.
   *
   * <p>The generated bytes are created using a cryptographically secure random number generator and
   * encoded as a Base64 string without padding.
   *
   * @param byteLength number of random bytes used to generate the token
   * @return Base64 encoded random token
   * @throws IllegalArgumentException if {@code byteLength} is negative
   */
  public static String generateToken(int byteLength) {
    if (byteLength < 0) {
      throw new IllegalArgumentException("Byte length cannot be negative");
    }

    byte[] bytes = new byte[byteLength];
    secureRandom.nextBytes(bytes);
    return Base64.getEncoder().withoutPadding().encodeToString(bytes);
  }

  /**
   * Generates a random token using the default token size.
   *
   * <p>Uses 64 random bytes, resulting in a high-entropy token suitable for authentication and
   * security-related purposes.
   *
   * @return Base64 encoded random token
   */
  public static String generateToken() {
    return generateToken(64);
  }
}
